services:

  django:
    build: ./
    command: [ "sh", "-c",
      "python manage.py migrate --no-input &&
       python manage.py collectstatic --no-input &&
       python manage.py runserver 0.0.0.0:8000" ]
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      ALLOWED_HOSTS: .localhost,127.0.0.1,::1
      DATABASE_URL: postgresql://user:password@postgres/database
      DEBUG: True
      SECRET_KEY: secret
    ports:
      - 8000:8000
    volumes:
      - ./static:/railway/static
      - ./templates:/railway/templates
      - ./website:/railway/website

  postgres:
    environment:
      POSTGRES_DB: database
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
    healthcheck:
      interval: 5s
      retries: 3
      test: pg_isready --dbname=$${POSTGRES_DB} --username=$${POSTGRES_USER}
      timeout: 15s
    image: postgres:latest
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
